script:
# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service 
# Use either `docker-compose` or individual `docker build` commands 
# Build 
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
# Tagging 
  - docker tag udagram-api-feed thebluesky37/udagram-api-feed:v1
  - docker tag udagram-api-user thebluesky37/udagram-api-user:v1
  - docker tag udagram-frontend thebluesky37/udagram-frontend:v2
  - docker tag reverseproxy thebluesky37/reverseproxy:v1
# Do similar for other three images``` 
# Push 
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push thebluesky37/udagram-api-feed:v1
  - docker push thebluesky37/udagram-api-user:v1
  - docker push thebluesky37/udagram-frontend:v2
  - docker push thebluesky37/reverseproxy:v1